/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// math-plotly-viewer/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MathPlotPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// math-plotly-viewer/constants.ts
var RESERVED_KEYWORDS = /* @__PURE__ */ new Set([
  "range",
  "domain",
  "step",
  "samples",
  "size",
  "theme",
  "color",
  "text",
  "title",
  "grid",
  "width",
  "height",
  "linewidth",
  "lw",
  "parameter",
  "param",
  "config",
  "x",
  "y",
  "z",
  "t",
  "theta",
  "phi",
  "rho",
  "r"
  // Math variables
]);
var GLOBAL_KEYWORDS = /* @__PURE__ */ new Set([
  "range",
  "domain",
  "size",
  "theme",
  "title",
  "grid",
  "width",
  "height",
  "text",
  "xrange",
  "yrange",
  "zrange",
  "trange",
  "phirange",
  "thetarange",
  "xstep",
  "ystep",
  "zstep",
  "tstep",
  "phistep",
  "thetastep"
]);
var DEFAULT_PALETTE = [
  "#4cc9f0",
  // Cyan
  "#f72585",
  // Pink/Magenta
  "#7209b7",
  // Purple
  "#4361ee",
  // Blue
  "#ffb703",
  // Yellow/Orange
  "#06d6a0",
  // Green
  "#ef476f"
  // Red/Pink
];
var DEFAULT_SETTINGS = {
  theme: "plotly_dark",
  renderQuality: 40,
  plotBackgroundColor: "rgba(0, 0, 0, 0)",
  curveColor: "#4cc9f0",
  lineWidth: 3,
  colorscale3D: "Viridis",
  defaultBlockWidth: "100%",
  defaultBlockHeight: "450px",
  defaultMobileBlockWidth: "100%",
  // 移动端默认宽度
  defaultMobileBlockHeight: "350px",
  // 移动端默认高度
  borderColor: "#333333",
  borderWidth: "1px",
  gridColor: "#444444",
  textColor: "#dcddde",
  defaultRangeMin: -10,
  defaultRangeMax: 10,
  plotFontSize: 12,
  mobileThreshold: 768
  // 移动端阈值
};

// math-plotly-viewer/math/parser.ts
var smartSplit = (str, delimiter) => {
  const parts = [];
  let current = "";
  let depth = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str[i];
    if (char === "(" || char === "[" || char === "{")
      depth++;
    else if (char === ")" || char === "]" || char === "}")
      depth--;
    if (char === delimiter && depth === 0) {
      if (current.trim() !== "")
        parts.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  if (current.trim() !== "")
    parts.push(current.trim());
  return parts;
};
var getVariables = (exprs) => {
  const vars = /* @__PURE__ */ new Set();
  exprs.forEach((expr) => {
    try {
      if (window.math) {
        window.math.parse(expr).traverse((node) => {
          if (node.type === "SymbolNode" && !window.math[node.name]) {
            vars.add(node.name);
          }
        });
      }
    } catch (e) {
    }
  });
  return vars;
};
function parseScript(source) {
  try {
    const math = window.math;
    const lines = source.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
    if (lines.length === 0)
      throw { code: "ERR_EMPTY", message: "Source is empty." };
    const globalConfig = {};
    const parametersMap = /* @__PURE__ */ new Map();
    const plotDefs = [];
    const paramKeys = [
      "range",
      "domain",
      "step",
      "samples",
      "size",
      "theme",
      "color",
      "text",
      "title",
      "grid",
      "width",
      "height",
      "linewidth",
      "lw",
      "xrange",
      "yrange",
      "zrange",
      "trange",
      "phirange",
      "thetarange",
      "xstep",
      "ystep",
      "zstep",
      "tstep",
      "phistep",
      "thetastep"
    ];
    lines.forEach((line) => {
      const parts = smartSplit(line, ",");
      const localConfig = {};
      let equationRaw = "";
      let processedParams = false;
      parts.forEach((part) => {
        const eqIdx = part.indexOf("=");
        let processed = false;
        if (eqIdx > -1) {
          const key = part.substring(0, eqIdx).trim().toLowerCase();
          const val = part.substring(eqIdx + 1).trim();
          if (key === "parameter" || key === "param") {
            processed = true;
            processedParams = true;
            const inner = val.replace(/[\[\]]/g, "");
            const pParts = inner.split(",").map((s) => s.trim());
            if (pParts.length < 3)
              throw { code: "ERR_PARAM_FMT", message: `Invalid parameter format: '${val}'. Expected [name, min, max, step?]` };
            const name = pParts[0];
            if (RESERVED_KEYWORDS.has(name))
              throw { code: "ERR_RESERVED", message: `Parameter name '${name}' is reserved.` };
            if (!isNaN(Number(name)))
              throw { code: "ERR_PARAM_NAME", message: `Parameter name '${name}' cannot be a number.` };
            const val1 = parseFloat(pParts[1]);
            const val2 = parseFloat(pParts[2]);
            const step = pParts[3] ? parseFloat(pParts[3]) : Math.abs(val2 - val1) / 50;
            if (isNaN(val1) || isNaN(val2))
              throw { code: "ERR_PARAM_VAL", message: `Invalid numeric range for parameter '${name}'` };
            const min = Math.min(val1, val2);
            const max = Math.max(val1, val2);
            parametersMap.set(name, {
              name,
              min,
              max,
              step: isNaN(step) ? (max - min) / 50 : step,
              value: min
            });
          } else if (paramKeys.includes(key)) {
            processed = true;
            if (GLOBAL_KEYWORDS.has(key)) {
              globalConfig[key] = val;
            } else {
              localConfig[key] = val;
            }
          }
        }
        if (!processed) {
          if (!equationRaw)
            equationRaw = part.trim();
        }
      });
      if (equationRaw) {
        const parametricMatch = equationRaw.match(/^\[(.*)\]$/);
        const isArrayInput = !!parametricMatch;
        const arrayExprs = isArrayInput ? smartSplit(parametricMatch[1], ",") : [];
        const variables = isArrayInput ? getVariables(arrayExprs) : getVariables([equationRaw]);
        parametersMap.forEach((_, name) => variables.delete(name));
        const isEquationR = equationRaw.split("=")[0].trim() === "r";
        const isEquationRho = equationRaw.split("=")[0].trim() === "rho";
        let type = "explicit2d";
        let equation = equationRaw;
        const has = (v) => variables.has(v);
        if (isArrayInput) {
          if (has("t") && !has("x") && !has("y")) {
            type = arrayExprs.length >= 3 ? "parametric3d" : "parametric2d";
          } else if (has("x") || has("y") || has("z")) {
            type = arrayExprs.length >= 3 ? "vector3d" : "vector2d";
          }
        } else {
          let isImplicit = equationRaw.includes("=");
          if (isEquationR)
            isImplicit = false;
          if (isEquationRho)
            isImplicit = false;
          if (has("phi") || has("rho") || isEquationRho)
            type = "spherical";
          else if (isEquationR && (has("z") || equationRaw.includes("z")))
            type = "cylindrical";
          else if (has("theta") || isEquationR)
            type = "polar";
          else if (isImplicit) {
            const sides = equationRaw.split("=");
            if (sides.length === 2)
              equation = `${sides[0]} - (${sides[1]})`;
            type = equation.includes("z") ? "implicit3d" : "implicit2d";
          } else if (equation.includes("z") || has("x") && has("y"))
            type = "explicit3d";
          else
            type = "explicit2d";
        }
        if (type === "spherical" && equationRaw.includes("="))
          equation = equationRaw.split("=")[1];
        if (type === "cylindrical" && equationRaw.includes("="))
          equation = equationRaw.split("=")[1];
        if (type === "polar" && equationRaw.includes("="))
          equation = equationRaw.split("=")[1];
        const compiled = {};
        if (isArrayInput) {
          if (arrayExprs[0])
            compiled.x = math.compile(arrayExprs[0]);
          if (arrayExprs[1])
            compiled.y = math.compile(arrayExprs[1]);
          if (arrayExprs[2])
            compiled.z = math.compile(arrayExprs[2]);
        } else {
          compiled.main = math.compile(equation);
        }
        plotDefs.push({ type, equation, arrayExprs, config: localConfig, compiled });
      }
    });
    if (plotDefs.length === 0 && parametersMap.size === 0) {
      throw { code: "ERR_NO_EQ", message: "No equation found." };
    }
    return {
      globalConfig,
      plots: plotDefs,
      parameters: Array.from(parametersMap.values())
    };
  } catch (e) {
    return {
      globalConfig: {},
      plots: [],
      parameters: [],
      error: e.code ? e : { code: "ERR_PARSE", message: e.message }
    };
  }
}

// math-plotly-viewer/math/compute.ts
function computePlot(parsed, params, settings) {
  try {
    let min = settings.defaultRangeMin;
    let max = settings.defaultRangeMax;
    const rawRange = parsed.globalConfig["range"] || parsed.globalConfig["domain"];
    if (rawRange) {
      const cleaned = rawRange.replace(/[\[\]\(\)]/g, "");
      const rp = cleaned.split(",").map((s) => parseFloat(s.trim()));
      if (!isNaN(rp[0]))
        min = rp[0];
      if (!isNaN(rp[1]))
        max = rp[1];
    }
    const parseRange = (str, defaultMin, defaultMax) => {
      if (!str)
        return { min: defaultMin, max: defaultMax };
      const cleaned = str.replace(/[\[\]\(\)]/g, "");
      const rp = cleaned.split(",").map((s) => parseFloat(s.trim()));
      const rMin = !isNaN(rp[0]) ? rp[0] : defaultMin;
      const rMax = !isNaN(rp[1]) ? rp[1] : defaultMax;
      return { min: rMin, max: rMax };
    };
    const getAxisRange = (varName, config) => {
      const specificKey = `${varName}range`;
      const specificVal = config[specificKey] || parsed.globalConfig[specificKey];
      if (specificVal)
        return parseRange(specificVal, min, max);
      const genericVal = config["range"] || config["domain"] || parsed.globalConfig["range"] || parsed.globalConfig["domain"];
      return parseRange(genericVal, min, max);
    };
    const getAxisResolution = (varName, range, config, defaultQuality, maxLimit = 5e3) => {
      const span = Math.abs(range.max - range.min);
      if (span === 0)
        return 1;
      const sKey = `${varName}step`;
      const sVal = config[sKey] || parsed.globalConfig[sKey];
      if (sVal)
        return Math.min(Math.floor(span / parseFloat(sVal)), maxLimit);
      const gStep = config["step"] || parsed.globalConfig["step"];
      if (gStep)
        return Math.min(Math.floor(span / parseFloat(gStep)), maxLimit);
      const gSamples = config["samples"] || parsed.globalConfig["samples"];
      if (gSamples)
        return Math.min(parseInt(gSamples), maxLimit);
      return defaultQuality;
    };
    const finalGridColor = parsed.globalConfig["grid"] || settings.gridColor;
    const finalTextColor = settings.textColor;
    const is3D = parsed.plots.some((p) => ["explicit3d", "parametric3d", "vector3d", "implicit3d", "spherical", "cylindrical"].includes(p.type));
    const topMargin = 10;
    const margin = is3D ? { l: 0, r: 0, t: topMargin, b: 0 } : { l: 60, r: 60, t: Math.max(topMargin, 40), b: 60 };
    const layout = {
      template: parsed.globalConfig["theme"] || settings.theme,
      paper_bgcolor: "rgba(0,0,0,0)",
      plot_bgcolor: "rgba(0,0,0,0)",
      margin,
      showlegend: false,
      // We use custom legend
      legend: { font: { color: finalTextColor }, bgcolor: "rgba(0,0,0,0)" },
      autosize: true,
      // 确保 Plotly 尝试自动调整
      hovermode: "closest"
    };
    const plotGroups = [];
    const evaluate = (compiledExpr, scope) => {
      const fullScope = Object.assign({}, params, scope);
      return compiledExpr.evaluate(fullScope);
    };
    parsed.plots.forEach((plot, index) => {
      const { type, compiled, config, arrayExprs, equation } = plot;
      const quality = config["samples"] ? parseInt(config["samples"]) : settings.renderQuality || 40;
      const defaultColor = DEFAULT_PALETTE[index % DEFAULT_PALETTE.length];
      const finalCurveColor = config["color"] || defaultColor;
      const lw = config["linewidth"] || config["lw"];
      const finalLineWidth = lw ? parseFloat(lw) : settings.lineWidth;
      const traceName = config["title"] || equation;
      const currentTraces = [];
      let currentTableData = null;
      if (type === "explicit2d") {
        const range = getAxisRange("x", config);
        const plotSteps = getAxisResolution("x", range, config, 250);
        const act = (range.max - range.min) / plotSteps;
        const xA = [], yA = [];
        const tableRows = [];
        for (let i = 0; i <= plotSteps; i++) {
          const x = range.min + i * act;
          let val = null;
          try {
            const v = evaluate(compiled.main, { x });
            if (typeof v === "number" && isFinite(v))
              val = v;
          } catch (e) {
          }
          xA.push(x);
          yA.push(val);
          tableRows.push([x, val]);
        }
        currentTraces.push({ x: xA, y: yA, type: "scatter", mode: "lines", name: traceName, line: { color: finalCurveColor, width: finalLineWidth, shape: "spline" } });
        currentTableData = { type: "series", headers: ["x", "y"], rows: tableRows };
      } else if (type === "explicit3d") {
        const xRange = getAxisRange("x", config);
        const yRange = getAxisRange("y", config);
        const xSteps = getAxisResolution("x", xRange, config, quality || 60);
        const ySteps = getAxisResolution("y", yRange, config, quality || 60);
        const tX = [], tY = [], tZ = [];
        for (let i = 0; i <= xSteps; i++)
          tX.push(xRange.min + i * (xRange.max - xRange.min) / xSteps);
        for (let i = 0; i <= ySteps; i++)
          tY.push(yRange.min + i * (yRange.max - yRange.min) / ySteps);
        for (let i = 0; i <= ySteps; i++) {
          const zR = [], y = tY[i];
          for (let j = 0; j <= xSteps; j++) {
            let val = NaN;
            try {
              const v = evaluate(compiled.main, { x: tX[j], y });
              if (typeof v === "number" && isFinite(v))
                val = v;
            } catch (e) {
            }
            zR.push(val);
          }
          tZ.push(zR);
        }
        currentTraces.push({ z: tZ, x: tX, y: tY, type: "surface", name: traceName, colorscale: settings.colorscale3D, showscale: index === 0, opacity: 0.9 });
        currentTableData = { type: "grid", x: tX, y: tY, z: tZ, labels: { x: "X", y: "Y" } };
        if (!layout.scene)
          layout.scene = {};
      } else if (type === "polar") {
        const range = getAxisRange("theta", config);
        const isDefault = range.min === settings.defaultRangeMin && range.max === settings.defaultRangeMax;
        const pMin = isDefault ? 0 : range.min;
        const pMax = isDefault ? 6.28 : range.max;
        const actualRange = { min: pMin, max: pMax };
        const steps = getAxisResolution("theta", actualRange, config, 500);
        const dTheta = (pMax - pMin) / steps;
        const rA = [], tA = [];
        const tableRows = [];
        for (let i = 0; i <= steps; i++) {
          const theta = pMin + i * dTheta;
          try {
            const r = evaluate(compiled.main, { theta });
            if (typeof r === "number" && isFinite(r)) {
              rA.push(r);
              tA.push(theta);
              tableRows.push([theta, r]);
            }
          } catch (e) {
          }
        }
        currentTraces.push({ type: "scatterpolar", r: rA, theta: tA, mode: "lines", name: traceName, thetaunit: "radians", line: { color: finalCurveColor, width: finalLineWidth } });
        layout.polar = { bgcolor: "rgba(0,0,0,0)", angularaxis: { thetaunit: "radians", direction: "counterclockwise" } };
        currentTableData = { type: "series", headers: ["theta", "r"], rows: tableRows };
      } else if (type === "parametric2d") {
        const range = getAxisRange("t", config);
        const steps = getAxisResolution("t", range, config, 500);
        const dt = (range.max - range.min) / steps;
        const xA = [], yA = [];
        const tableRows = [];
        for (let i = 0; i <= steps; i++) {
          const t = range.min + i * dt;
          let xv = NaN, yv = NaN;
          try {
            xv = evaluate(compiled.x, { t });
            yv = evaluate(compiled.y, { t });
          } catch (e) {
          }
          if (isFinite(xv) && isFinite(yv)) {
            xA.push(xv);
            yA.push(yv);
            tableRows.push([t, xv, yv]);
          } else {
            xA.push(null);
            yA.push(null);
          }
        }
        currentTraces.push({ type: "scatter", mode: "lines", x: xA, y: yA, name: traceName, line: { width: finalLineWidth, color: finalCurveColor, shape: "spline" } });
        currentTableData = { type: "series", headers: ["t", "x", "y"], rows: tableRows };
      } else if (type === "parametric3d") {
        const range = getAxisRange("t", config);
        const steps = getAxisResolution("t", range, config, 500);
        const dt = (range.max - range.min) / steps;
        const xA = [], yA = [], zA = [];
        const tableRows = [];
        for (let i = 0; i <= steps; i++) {
          const t = range.min + i * dt;
          let xv = NaN, yv = NaN, zv = NaN;
          try {
            xv = evaluate(compiled.x, { t });
            yv = evaluate(compiled.y, { t });
            zv = evaluate(compiled.z, { t });
          } catch (e) {
          }
          if (isFinite(xv) && isFinite(yv) && isFinite(zv)) {
            xA.push(xv);
            yA.push(yv);
            zA.push(zv);
            tableRows.push([t, xv, yv, zv]);
          } else {
            xA.push(null);
            yA.push(null);
            zA.push(null);
          }
        }
        currentTraces.push({ type: "scatter3d", mode: "lines", x: xA, y: yA, z: zA, name: traceName, line: { width: finalLineWidth * 2, color: finalCurveColor } });
        currentTableData = { type: "series", headers: ["t", "x", "y", "z"], rows: tableRows };
      } else if (type === "spherical") {
        let rTheta = getAxisRange("theta", config);
        let rPhi = getAxisRange("phi", config);
        const defMin = settings.defaultRangeMin;
        const defMax = settings.defaultRangeMax;
        if (rTheta.min === defMin && rTheta.max === defMax)
          rTheta = { min: 0, max: 6.28 };
        if (rPhi.min === defMin && rPhi.max === defMax)
          rPhi = { min: 0, max: Math.PI };
        const thetaSteps = getAxisResolution("theta", rTheta, config, quality);
        const phiSteps = getAxisResolution("phi", rPhi, config, quality);
        const thetaVals = [], phiVals = [];
        for (let i = 0; i <= thetaSteps; i++)
          thetaVals.push(rTheta.min + i * (rTheta.max - rTheta.min) / thetaSteps);
        for (let i = 0; i <= phiSteps; i++)
          phiVals.push(rPhi.min + i * (rPhi.max - rPhi.min) / phiSteps);
        const xM = [], yM = [], zM = [], rhoM = [];
        for (let i = 0; i < phiVals.length; i++) {
          const phi = phiVals[i];
          const xR = [], yR = [], zR = [], rhoR = [];
          for (let j = 0; j < thetaVals.length; j++) {
            const theta = thetaVals[j];
            let valRho = NaN;
            try {
              const r = evaluate(compiled.main, { theta, phi });
              if (isFinite(r))
                valRho = r;
            } catch (e) {
            }
            if (!isNaN(valRho)) {
              xR.push(valRho * Math.sin(phi) * Math.cos(theta));
              yR.push(valRho * Math.sin(phi) * Math.sin(theta));
              zR.push(valRho * Math.cos(phi));
              rhoR.push(valRho);
            } else {
              xR.push(NaN);
              yR.push(NaN);
              zR.push(NaN);
              rhoR.push(NaN);
            }
          }
          xM.push(xR);
          yM.push(yR);
          zM.push(zR);
          rhoM.push(rhoR);
        }
        currentTraces.push({ type: "surface", x: xM, y: yM, z: zM, name: traceName, colorscale: settings.colorscale3D, showscale: index === 0 });
        layout.scene = { xaxis: { title: "X" }, yaxis: { title: "Y" }, zaxis: { title: "Z" }, aspectmode: "data" };
        currentTableData = { type: "grid", x: thetaVals, y: phiVals, z: rhoM, labels: { x: "\u03B8", y: "\u03C6" } };
      } else if (type === "cylindrical") {
        const rZ = getAxisRange("z", config);
        let rTheta = getAxisRange("theta", config);
        const defMin = settings.defaultRangeMin;
        const defMax = settings.defaultRangeMax;
        if (rTheta.min === defMin && rTheta.max === defMax)
          rTheta = { min: 0, max: 2 * Math.PI };
        if (rZ.min === defMin && rZ.max === defMax) {
          rZ.min = 0;
          rZ.max = 10;
        }
        const zSteps = getAxisResolution("z", rZ, config, quality);
        const thetaSteps = getAxisResolution("theta", rTheta, config, quality);
        const zVals = [], thetaVals = [];
        for (let i = 0; i <= zSteps; i++)
          zVals.push(rZ.min + i * (rZ.max - rZ.min) / zSteps);
        for (let i = 0; i <= thetaSteps; i++)
          thetaVals.push(rTheta.min + i * (rTheta.max - rTheta.min) / thetaSteps);
        const xM = [], yM = [], zM = [], rM = [];
        for (let i = 0; i < zVals.length; i++) {
          const z = zVals[i];
          const xR = [], yR = [], zR = [], rRow = [];
          for (let j = 0; j < thetaVals.length; j++) {
            const theta = thetaVals[j];
            let valR = NaN;
            try {
              const r = evaluate(compiled.main, { z, theta });
              if (isFinite(r))
                valR = r;
            } catch (e) {
            }
            if (!isNaN(valR)) {
              xR.push(valR * Math.cos(theta));
              yR.push(valR * Math.sin(theta));
              zR.push(z);
              rRow.push(valR);
            } else {
              xR.push(NaN);
              yR.push(NaN);
              zR.push(NaN);
              rRow.push(null);
            }
          }
          xM.push(xR);
          yM.push(yR);
          zM.push(zR);
          rM.push(rRow);
        }
        currentTraces.push({ type: "surface", x: xM, y: yM, z: zM, name: traceName, colorscale: settings.colorscale3D, showscale: index === 0 });
        layout.scene = { xaxis: { title: "X" }, yaxis: { title: "Y" }, zaxis: { title: "Z" }, aspectmode: "data" };
        currentTableData = { type: "grid", x: thetaVals, y: zVals, z: rM, labels: { x: "\u03B8", y: "Z" } };
      } else if (type === "implicit2d") {
        const xR = getAxisRange("x", config);
        const yR = getAxisRange("y", config);
        const xSteps = getAxisResolution("x", xR, config, 85);
        const ySteps = getAxisResolution("y", yR, config, 85);
        const xArr = [], yArr = [], zMatrix = [];
        const xSpan = xR.max - xR.min;
        const ySpan = yR.max - yR.min;
        for (let i = 0; i <= xSteps; i++)
          xArr.push(xR.min + i * (xSpan / xSteps));
        for (let i = 0; i <= ySteps; i++) {
          const row = [];
          const y = yR.min + i * (ySpan / ySteps);
          yArr.push(y);
          for (let j = 0; j <= xSteps; j++) {
            const x = xArr[j];
            let val = null;
            try {
              const v = evaluate(compiled.main, { x, y });
              if (isFinite(v))
                val = v;
            } catch (e) {
            }
            row.push(val);
          }
          zMatrix.push(row);
        }
        currentTraces.push({ z: zMatrix, x: xArr, y: yArr, type: "contour", name: traceName, showscale: false, contours: { coloring: "none", showlines: true, start: 0, end: 0, size: 0 }, line: { width: finalLineWidth, color: finalCurveColor }, hovertemplate: "x: %{x:.4f}<br>y: %{y:.4f}<extra></extra>" });
        layout.xaxis = { scaleanchor: "x", scaleratio: 1 };
        currentTableData = { type: "grid", x: xArr, y: yArr, z: zMatrix, labels: { x: "X", y: "Y" } };
      } else if (type === "implicit3d") {
        const xR = getAxisRange("x", config);
        const yR = getAxisRange("y", config);
        const zR = getAxisRange("z", config);
        const targetPoints = quality * 200;
        const xA = [], yA = [], zA = [];
        const epsilon = 1e-3;
        const getGradient = (x, y, z, val) => {
          const fx = evaluate(compiled.main, { x: x + epsilon, y, z });
          const fy = evaluate(compiled.main, { x, y: y + epsilon, z });
          const fz = evaluate(compiled.main, { x, y, z: z + epsilon });
          return [(fx - val) / epsilon, (fy - val) / epsilon, (fz - val) / epsilon];
        };
        let attempts = 0;
        const maxAttempts = targetPoints * 3;
        const rnd = (min2, max2) => min2 + Math.random() * (max2 - min2);
        while (xA.length < targetPoints && attempts < maxAttempts) {
          attempts++;
          let px = rnd(xR.min, xR.max), py = rnd(yR.min, yR.max), pz = rnd(zR.min, zR.max);
          let converged = false;
          for (let iter = 0; iter < 5; iter++) {
            let val;
            try {
              val = evaluate(compiled.main, { x: px, y: py, z: pz });
            } catch (e) {
              break;
            }
            if (!isFinite(val))
              break;
            if (Math.abs(val) < 0.05) {
              converged = true;
              break;
            }
            const grad = getGradient(px, py, pz, val);
            const magSq = grad[0] * grad[0] + grad[1] * grad[1] + grad[2] * grad[2];
            if (magSq < 1e-6)
              break;
            const step = val / magSq;
            px -= step * grad[0];
            py -= step * grad[1];
            pz -= step * grad[2];
            if (px < xR.min * 1.5 || px > xR.max * 1.5 || py < yR.min * 1.5 || py > yR.max * 1.5 || pz < zR.min * 1.5 || pz > zR.max * 1.5) {
              converged = false;
              break;
            }
          }
          if (converged) {
            xA.push(px);
            yA.push(py);
            zA.push(pz);
          }
        }
        currentTraces.push({ type: "scatter3d", mode: "markers", x: xA, y: yA, z: zA, name: traceName, marker: { size: 2, color: zA, colorscale: settings.colorscale3D, opacity: 0.7, showscale: index === 0 } });
        layout.scene = { xaxis: { title: "X" }, yaxis: { title: "Y" }, zaxis: { title: "Z" }, camera: { eye: { x: 1.5, y: 1.5, z: 1.5 } } };
        currentTableData = { type: "series", headers: ["x", "y", "z"], rows: [] };
      } else if (type === "vector2d" || type === "vector3d") {
        const isV3D = type === "vector3d";
        const xR = getAxisRange("x", config);
        const yR = getAxisRange("y", config);
        const zR = isV3D ? getAxisRange("z", config) : { min: 0, max: 0 };
        const xSteps = getAxisResolution("x", xR, config, isV3D ? 8 : 20);
        const ySteps = getAxisResolution("y", yR, config, isV3D ? 8 : 20);
        const zSteps = isV3D ? getAxisResolution("z", zR, config, 8) : 1;
        const xA = [], yA = [], zA = [], uA = [], vA = [], wA = [];
        const tableRows = [];
        const cX = compiled.x;
        const cY = compiled.y;
        const cZ = isV3D ? compiled.z : null;
        const dx = (xR.max - xR.min) / xSteps;
        const dy = (yR.max - yR.min) / ySteps;
        const dz = isV3D ? (zR.max - zR.min) / zSteps : 0;
        for (let i = 0; i <= xSteps; i++) {
          for (let j = 0; j <= ySteps; j++) {
            const x = xR.min + i * dx;
            const y = yR.min + j * dy;
            if (isV3D && cZ) {
              for (let k = 0; k <= zSteps; k++) {
                const z = zR.min + k * dz;
                try {
                  const s = Object.assign({}, params, { x, y, z });
                  const u = cX.evaluate(s), v = cY.evaluate(s), w = cZ.evaluate(s);
                  if (isFinite(u) && isFinite(v) && isFinite(w)) {
                    xA.push(x);
                    yA.push(y);
                    zA.push(z);
                    uA.push(u);
                    vA.push(v);
                    wA.push(w);
                    const mag = Math.sqrt(u * u + v * v + w * w);
                    tableRows.push([x, y, z, u, v, w, mag]);
                  }
                } catch (e) {
                }
              }
            } else {
              try {
                const s = Object.assign({}, params, { x, y, z: 0 });
                const u = cX.evaluate(s), v = cY.evaluate(s);
                if (isFinite(u) && isFinite(v)) {
                  const m = Math.sqrt(u * u + v * v);
                  xA.push(x);
                  yA.push(y);
                  uA.push(u);
                  vA.push(v);
                  wA.push(m);
                  tableRows.push([x, y, u, v, m]);
                }
              } catch (e) {
              }
            }
          }
        }
        if (isV3D) {
          currentTableData = { type: "series", headers: ["x", "y", "z", "u", "v", "w", "|v|"], rows: tableRows };
          currentTraces.push({ type: "cone", x: xA, y: yA, z: zA, u: uA, v: vA, w: wA, name: traceName, sizemode: "scaled", sizeref: 0.5, colorscale: settings.colorscale3D, showscale: index === 0 });
        } else {
          currentTableData = { type: "series", headers: ["x", "y", "u", "v", "|v|"], rows: tableRows };
          const lX = [], lY = [], hX = [], hY = [], ang = [], col = [];
          let maxMag = 0;
          wA.forEach((m) => maxMag = Math.max(maxMag, m));
          const scale = maxMag > 0 ? dx * 0.9 / maxMag : 1;
          for (let i = 0; i < xA.length; i++) {
            const x = xA[i], y = yA[i], u = uA[i], v = vA[i], m = wA[i];
            const su = u * scale, sv = v * scale;
            lX.push(x, x + su, null);
            lY.push(y, y + sv, null);
            hX.push(x + su);
            hY.push(y + sv);
            col.push(m);
            ang.push(Math.atan2(v, u) * 180 / Math.PI - 90);
          }
          currentTraces.push({ type: "scatter", mode: "lines", x: lX, y: lY, name: traceName + " (lines)", line: { color: finalCurveColor, width: finalLineWidth * 0.5 }, hoverinfo: "skip", showlegend: false });
          currentTraces.push({ type: "scatter", mode: "markers", x: hX, y: hY, name: traceName, marker: { symbol: "triangle-up", size: 8, angle: ang, color: col, colorscale: settings.colorscale3D, showscale: index === 0 } });
          layout.xaxis = { scaleanchor: "x", scaleratio: 1 };
        }
      }
      if (currentTraces.length > 0) {
        if (currentTableData) {
          currentTableData.name = traceName;
          currentTableData.color = finalCurveColor;
        }
        plotGroups.push({
          traces: currentTraces,
          table: currentTableData,
          name: traceName,
          color: finalCurveColor
        });
      }
    });
    const axisStyle = {
      gridcolor: finalGridColor,
      zerolinecolor: finalGridColor,
      linecolor: finalGridColor,
      tickcolor: finalGridColor,
      title: { font: { color: finalTextColor } },
      tickfont: { color: finalTextColor }
    };
    if (layout.scene) {
      layout.scene.xaxis = Object.assign({}, layout.scene.xaxis, axisStyle);
      layout.scene.yaxis = Object.assign({}, layout.scene.yaxis, axisStyle);
      layout.scene.zaxis = Object.assign({}, layout.scene.zaxis, axisStyle);
    } else if (layout.polar) {
      layout.polar.radialaxis = Object.assign({}, layout.polar.radialaxis, axisStyle);
      layout.polar.angularaxis = Object.assign({}, layout.polar.angularaxis, axisStyle);
    } else {
      layout.xaxis = Object.assign({}, layout.xaxis, axisStyle);
      layout.yaxis = Object.assign({}, layout.yaxis, axisStyle);
    }
    return { plotGroups, layout };
  } catch (e) {
    return { plotGroups: [], layout: {}, error: e.message || String(e) };
  }
}

// math-plotly-viewer/ui/renderer.ts
function renderError(container, code, msg) {
  container.innerHTML = "";
  container.style.height = "auto";
  const errEl = container.createEl("div", { cls: "mathplot-error" });
  errEl.innerHTML = `<strong style="display:block; margin-bottom:4px;">Error [${code}]</strong>${msg}`;
}
function renderTable(container, tableData, settings) {
  container.innerHTML = "";
  const borderColor = settings.gridColor;
  const textColor = settings.textColor;
  const curveColor = tableData.color || settings.curveColor;
  const fontSize = settings.plotFontSize;
  const headerStyle = `position: sticky; top: 0; background: #222; z-index: 5; border: 1px solid ${borderColor}; padding: 6px; color: ${curveColor}; text-align: left; font-size: ${fontSize}px;`;
  const cellStyleNum = `border: 1px solid ${borderColor}; padding: 4px 6px; color: ${textColor}; text-align: right; opacity: 0.8; font-size: ${fontSize}px;`;
  const cellStyle = `border: 1px solid ${borderColor}; padding: 4px 6px; color: ${textColor}; font-size: ${fontSize}px;`;
  const wrapper = container.createEl("div", { cls: "mathplot-table-wrapper" });
  const table = wrapper.createEl("table", { cls: "mathplot-data-table" });
  table.style.color = textColor;
  if (tableData.type === "grid" && tableData.labels && tableData.x && tableData.y && tableData.z) {
    const thead = table.createEl("thead");
    const hr = thead.createEl("tr");
    hr.createEl("th", { text: `${tableData.labels.y}\\${tableData.labels.x}`, attr: { style: headerStyle + " left: 0; z-index: 10;" } });
    tableData.x.forEach((x) => hr.createEl("th", { text: x.toFixed(2), attr: { style: headerStyle } }));
    const tbody = table.createEl("tbody");
    tableData.y.forEach((y, i) => {
      const tr = tbody.createEl("tr");
      if (i % 2 === 1)
        tr.classList.add("mathplot-tr-odd");
      tr.createEl("td", { text: y.toFixed(2), attr: { style: `border: 1px solid ${borderColor}; padding: 4px; font-weight:bold; background: #222; position: sticky; left: 0; z-index: 2; color: ${textColor}; font-size: ${fontSize}px;` } });
      tableData.z[i].forEach((z) => {
        tr.createEl("td", { text: z !== null && !isNaN(z) ? z.toFixed(2) : "", attr: { style: cellStyleNum } });
      });
    });
  } else if (tableData.headers && tableData.rows) {
    const thead = table.createEl("thead");
    const tr = thead.createEl("tr");
    tr.createEl("th", { text: "#", attr: { style: headerStyle + " width: 40px;" } });
    tableData.headers.forEach((h) => {
      tr.createEl("th", { text: h, attr: { style: headerStyle } });
    });
    const tbody = table.createEl("tbody");
    const maxRows = 2e3;
    const rowsToRender = tableData.rows.slice(0, maxRows);
    rowsToRender.forEach((row, i) => {
      const tr2 = tbody.createEl("tr");
      if (i % 2 === 1)
        tr2.classList.add("mathplot-tr-odd");
      tr2.createEl("td", { text: String(i + 1), attr: { style: cellStyleNum + " text-align: center; opacity: 0.5;" } });
      row.forEach((cell) => {
        let txt = "-";
        let style = cellStyleNum;
        if (typeof cell === "number")
          txt = cell.toFixed(4);
        else if (cell !== null && cell !== void 0) {
          txt = String(cell);
          style = cellStyle;
        }
        tr2.createEl("td", { text: txt, attr: { style } });
      });
    });
    if (tableData.rows.length > maxRows) {
      container.createEl("div", { text: `Showing first ${maxRows} of ${tableData.rows.length} rows.`, cls: "mathplot-table-info" });
    }
  }
}
function renderSlider(container, param, settings, onUpdate, onPlayStateChange) {
  const wrapper = container.createEl("div", { cls: "mathplot-slider-wrapper" });
  wrapper.style.color = settings.textColor;
  const playBtn = wrapper.createEl("button", { text: "Play", cls: "mathplot-btn mathplot-play-btn" });
  wrapper.createEl("span", { text: param.name + ":", cls: "mathplot-slider-label" });
  const slider = wrapper.createEl("input", { attr: { type: "range" }, cls: "mathplot-slider-input" });
  slider.min = String(param.min);
  slider.max = String(param.max);
  slider.step = String(param.step);
  slider.value = String(param.value);
  const valDisplay = wrapper.createEl("span", { text: param.value.toFixed(2), cls: "mathplot-slider-val" });
  let isPlaying = false;
  let animId;
  let direction = 1;
  let lastTime = 0;
  const fps = 15;
  const interval = 1e3 / fps;
  playBtn.onclick = () => {
    isPlaying = !isPlaying;
    playBtn.innerText = isPlaying ? "Pause" : "Play";
    if (isPlaying)
      playBtn.classList.add("active");
    else
      playBtn.classList.remove("active");
    if (onPlayStateChange)
      onPlayStateChange(isPlaying);
    if (isPlaying) {
      const animate = (time) => {
        if (!document.body.contains(wrapper))
          return;
        if (time - lastTime > interval) {
          lastTime = time;
          let next = param.value + param.step * direction;
          if (next >= param.max) {
            next = param.max;
            direction = -1;
          } else if (next <= param.min) {
            next = param.min;
            direction = 1;
          }
          next = Math.round(next * 1e4) / 1e4;
          param.value = next;
          slider.value = String(next);
          valDisplay.innerText = next.toFixed(2);
          onUpdate(next);
        }
        if (isPlaying)
          animId = requestAnimationFrame(animate);
      };
      animId = requestAnimationFrame(animate);
    } else {
      cancelAnimationFrame(animId);
    }
  };
  slider.oninput = (e) => {
    const v = parseFloat(e.target.value);
    param.value = v;
    valDisplay.innerText = v.toFixed(2);
    onUpdate(v);
    if (isPlaying) {
      isPlaying = false;
      if (onPlayStateChange)
        onPlayStateChange(false);
      playBtn.innerText = "Play";
      playBtn.classList.remove("active");
      cancelAnimationFrame(animId);
    }
  };
}
function renderPlot(container, source, settings, renderChild) {
  if (!window.math || !window.Plotly) {
    container.createEl("div", { text: "Libraries loading..." });
    return;
  }
  const Plotly = window.Plotly;
  container.innerHTML = "";
  container.dataset.source = source;
  const parsed = parseScript(source);
  const mobileQuery = window.matchMedia(`(max-width: ${settings.mobileThreshold || 768}px)`);
  const updateContainerSize = () => {
    const isMobile = mobileQuery.matches;
    const defaultW = isMobile ? settings.defaultMobileBlockWidth : settings.defaultBlockWidth;
    const defaultH = isMobile ? settings.defaultMobileBlockHeight : settings.defaultBlockHeight;
    let targetWidth = parsed.globalConfig["width"] || (parsed.globalConfig["size"] ? parsed.globalConfig["size"].split(",")[0] : null) || defaultW;
    let targetHeight = parsed.globalConfig["height"] || (parsed.globalConfig["size"] ? parsed.globalConfig["size"].split(",")[1] : null) || defaultH;
    container.style.width = targetWidth;
    const plotDiv2 = container.querySelector(".plot-div");
    if (plotDiv2) {
      plotDiv2.style.height = targetHeight;
      try {
        if (plotDiv2._fullLayout && plotDiv2.clientWidth > 0 && plotDiv2.clientHeight > 0) {
          Plotly.Plots.resize(plotDiv2);
        }
      } catch (e) {
        console.warn("MathPlotly resize skipped:", e);
      }
    }
  };
  container.style.border = `${settings.borderWidth} solid ${settings.borderColor}`;
  container.style.backgroundColor = settings.plotBackgroundColor === "rgba(0, 0, 0, 0)" ? "#111" : settings.plotBackgroundColor;
  const onMediaChange = () => updateContainerSize();
  mobileQuery.addEventListener("change", onMediaChange);
  const resizeObserver = new ResizeObserver(() => {
    const plotDiv2 = container.querySelector(".plot-div");
    if (plotDiv2) {
      try {
        if (plotDiv2._fullLayout && plotDiv2.clientWidth > 0 && plotDiv2.clientHeight > 0) {
          Plotly.Plots.resize(plotDiv2);
        }
      } catch (e) {
        console.warn("MathPlotly resize skipped:", e);
      }
    }
  });
  resizeObserver.observe(container);
  if (renderChild) {
    renderChild.registerOnUnload(() => {
      mobileQuery.removeEventListener("change", onMediaChange);
      resizeObserver.disconnect();
    });
  }
  if (parsed.error) {
    renderError(container, parsed.error.code, parsed.error.message);
    return;
  }
  const customTitle = parsed.globalConfig["text"] || parsed.globalConfig["title"];
  const hasMultiplePlots = parsed.plots.length > 1;
  const showHeader = !!customTitle || hasMultiplePlots;
  let headerDiv = null;
  let legendContainer = null;
  if (showHeader) {
    headerDiv = container.createEl("div", { cls: "mathplot-header" });
    headerDiv.style.borderBottom = `1px solid ${settings.borderColor}`;
    const titleSpan = headerDiv.createEl("span", { text: customTitle || "", cls: "mathplot-title-text" });
    titleSpan.style.color = settings.textColor;
    legendContainer = headerDiv.createEl("div", { cls: "mathplot-legend-container" });
  }
  const plotDiv = container.createEl("div", { cls: "plot-div" });
  updateContainerSize();
  const controlsDiv = container.createEl("div", { cls: "mathplot-controls" });
  controlsDiv.style.borderTop = `1px solid ${settings.borderColor}`;
  const slidersContainer = controlsDiv.createEl("div", { cls: "mathplot-sliders-container" });
  const tableActionContainer = controlsDiv.createEl("div", { cls: "mathplot-table-action" });
  const toggleBtn = tableActionContainer.createEl("button", { text: "Show Table", cls: "mathplot-btn" });
  const tableContainer = container.createEl("div", { cls: "mathplot-table" });
  tableContainer.style.borderTop = `1px solid ${settings.borderColor}`;
  const currentParams = {};
  parsed.parameters.forEach((p) => currentParams[p.name] = p.value);
  let isTableVisible = false;
  let activeDatasetIndex = -1;
  let latestResult = null;
  let activeAnimations = 0;
  const mergeTableData = (datasets) => {
    const validDatasets = datasets.filter((d) => d !== null);
    if (!validDatasets || validDatasets.length === 0)
      return null;
    if (validDatasets.length === 1)
      return validDatasets[0];
    if (validDatasets.some((d) => d.type !== "series"))
      return validDatasets[0];
    const base = validDatasets[0];
    if (!base.headers || !base.rows)
      return null;
    const domainLabel = base.headers[0];
    const mergedHeaders = [domainLabel];
    validDatasets.forEach((ds) => {
      if (ds.headers) {
        for (let i = 1; i < ds.headers.length; i++) {
          mergedHeaders.push(`${ds.headers[i]} (${ds.name})`);
        }
      }
    });
    const rowCount = base.rows.length;
    const mergedRows = [];
    for (let r = 0; r < rowCount; r++) {
      const row = [base.rows[r][0]];
      validDatasets.forEach((ds) => {
        if (ds.rows && ds.rows[r]) {
          for (let c = 1; c < ds.rows[r].length; c++) {
            row.push(ds.rows[r][c]);
          }
        } else if (ds.headers) {
          for (let c = 1; c < ds.headers.length; c++)
            row.push(null);
        }
      });
      mergedRows.push(row);
    }
    return {
      type: "series",
      headers: mergedHeaders,
      rows: mergedRows,
      color: settings.textColor
    };
  };
  const updateTableButtonState = () => {
    if (activeAnimations > 0) {
      toggleBtn.disabled = true;
      toggleBtn.classList.add("mathplot-btn-disabled");
      toggleBtn.innerText = "Playing...";
    } else {
      toggleBtn.disabled = false;
      toggleBtn.classList.remove("mathplot-btn-disabled");
      toggleBtn.innerText = isTableVisible ? "Hide Table" : "Show Table";
    }
  };
  const styleLegendBtn = (btn, active, activeColor, activeText) => {
    if (active) {
      btn.style.backgroundColor = activeColor;
      btn.style.color = activeText;
      if (activeColor.startsWith("#0") || activeColor === "black" || activeColor.includes("0,0,0") || activeColor === "#444") {
        btn.style.color = "#fff";
      }
      btn.classList.add("active");
    } else {
      btn.style.backgroundColor = "rgba(255,255,255,0.1)";
      btn.style.color = "#888";
      btn.classList.remove("active");
    }
  };
  const renderHeaderLegend = () => {
    if (!legendContainer || !latestResult || !latestResult.plotGroups)
      return;
    legendContainer.innerHTML = "";
    if (latestResult.plotGroups.length > 0) {
      const groups = latestResult.plotGroups;
      if (groups.length > 1) {
        const isAllActive = activeDatasetIndex === -1;
        const allBtn = legendContainer.createEl("button", { text: "ALL", cls: "mathplot-legend-btn" });
        styleLegendBtn(allBtn, isAllActive, "#444", "#ccc");
        allBtn.onclick = () => {
          activeDatasetIndex = -1;
          renderHeaderLegend();
          updatePlotVisuals();
        };
        groups.forEach((g, idx) => {
          const isActive = idx === activeDatasetIndex;
          const btn = legendContainer.createEl("button", { text: g.name || `Eq ${idx + 1}`, cls: "mathplot-legend-btn" });
          styleLegendBtn(btn, isActive, g.color, "#000");
          btn.onclick = () => {
            activeDatasetIndex = idx;
            renderHeaderLegend();
            updatePlotVisuals();
          };
        });
      }
    }
  };
  toggleBtn.onclick = () => {
    isTableVisible = !isTableVisible;
    updateTableButtonState();
    if (isTableVisible) {
      tableContainer.style.display = "flex";
      renderTableContent();
    } else {
      tableContainer.style.display = "none";
    }
    requestAnimationFrame(() => {
      updatePlotVisuals();
    });
  };
  const renderTableContent = () => {
    if (!latestResult || !tableContainer)
      return;
    let dataToShow = null;
    if (activeDatasetIndex === -1) {
      const allTables = latestResult.plotGroups.map((g) => g.table);
      dataToShow = mergeTableData(allTables);
    } else {
      if (latestResult.plotGroups[activeDatasetIndex]) {
        dataToShow = latestResult.plotGroups[activeDatasetIndex].table;
      }
    }
    if (dataToShow) {
      renderTable(tableContainer, dataToShow, settings);
    } else {
      tableContainer.innerHTML = "<div class='mathplot-no-data'>No data available.</div>";
    }
  };
  const updatePlotVisuals = () => {
    if (!latestResult)
      return;
    let activeTraces = [];
    if (activeDatasetIndex === -1) {
      activeTraces = latestResult.plotGroups.flatMap((g) => g.traces);
    } else {
      if (latestResult.plotGroups[activeDatasetIndex]) {
        activeTraces = latestResult.plotGroups[activeDatasetIndex].traces;
      }
    }
    const finalLayout = Object.assign({}, latestResult.layout, {
      showlegend: false,
      font: {
        family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
        color: settings.textColor,
        size: settings.plotFontSize
      },
      autosize: true,
      uirevision: "mathplot-animation"
    });
    Plotly.react(plotDiv, activeTraces, finalLayout, {
      responsive: true,
      displayModeBar: false
    });
    if (isTableVisible && activeAnimations === 0) {
      renderTableContent();
    }
  };
  const updatePlot = () => {
    const result = computePlot(parsed, currentParams, settings);
    latestResult = result;
    if (result.error) {
      renderError(plotDiv, "ERR_EVAL", typeof result.error === "string" ? result.error : result.error.message || String(result.error));
      return;
    }
    if (result.plotGroups.length === 0) {
      renderError(plotDiv, "ERR_NO_DATA", "No data generated");
      return;
    }
    const hasSliders = parsed.parameters.length > 0;
    const hasData = result.plotGroups.length > 0;
    if (hasSliders || hasData) {
      controlsDiv.style.display = "flex";
      slidersContainer.style.display = hasSliders ? "flex" : "none";
      tableActionContainer.style.display = hasData ? "flex" : "none";
    } else {
      controlsDiv.style.display = "none";
    }
    renderHeaderLegend();
    updatePlotVisuals();
  };
  if (parsed.parameters.length > 0) {
    parsed.parameters.forEach((param) => {
      renderSlider(
        slidersContainer,
        param,
        settings,
        (newVal) => {
          currentParams[param.name] = newVal;
          updatePlot();
        },
        (playing) => {
          if (playing)
            activeAnimations++;
          else
            activeAnimations--;
          if (activeAnimations < 0)
            activeAnimations = 0;
          updateTableButtonState();
        }
      );
    });
  }
  updatePlot();
}

// math-plotly-viewer/ui/settingsTab.ts
var import_obsidian = require("obsidian");
var MathPlotSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.innerHTML = "";
    containerEl.createEl("h2", { text: "MathPlot Settings" });
    containerEl.createEl("h3", { text: "Layout & Dimensions" });
    new import_obsidian.Setting(containerEl).setName("Block Width").setDesc("Default width of the plot container (e.g. 100%)").addSlider((slider) => slider.setLimits(20, 100, 5).setValue(parseInt(this.plugin.settings.defaultBlockWidth) || 100).onChange(async (value) => {
      this.plugin.settings.defaultBlockWidth = value + "%";
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Mobile Threshold").setDesc("Screen width (px) below which plots will take mobile dimensions.").addSlider((slider) => slider.setLimits(300, 1200, 50).setValue(this.plugin.settings.mobileThreshold || 768).onChange(async (value) => {
      this.plugin.settings.mobileThreshold = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Mobile Block Width").setDesc("Default width on mobile devices (e.g. 100%)").addText((text) => text.setValue(this.plugin.settings.defaultMobileBlockWidth || "100%").onChange(async (value) => {
      this.plugin.settings.defaultMobileBlockWidth = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Block Height").setDesc("Default height of the plot container (px)").addSlider((slider) => slider.setLimits(300, 1200, 50).setValue(parseInt(this.plugin.settings.defaultBlockHeight) || 450).onChange(async (value) => {
      this.plugin.settings.defaultBlockHeight = value + "px";
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Mobile Block Height").setDesc("Default height on mobile devices (e.g. 350px)").addText((text) => text.setValue(this.plugin.settings.defaultMobileBlockHeight || "350px").onChange(async (value) => {
      this.plugin.settings.defaultMobileBlockHeight = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Border Width").setDesc("Thickness of the plot border (px)").addSlider((slider) => slider.setLimits(0, 10, 1).setValue(parseInt(this.plugin.settings.borderWidth) || 1).onChange(async (value) => {
      this.plugin.settings.borderWidth = value + "px";
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Border Color").setDesc("Color of the plot border").addColorPicker((color) => color.setValue(this.plugin.settings.borderColor).onChange(async (value) => {
      this.plugin.settings.borderColor = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Visual Style" });
    new import_obsidian.Setting(containerEl).setName("Plot Font Size").setDesc("Base font size for the plot labels and text (px)").addSlider((slider) => slider.setLimits(8, 24, 1).setValue(this.plugin.settings.plotFontSize).onChange(async (value) => {
      this.plugin.settings.plotFontSize = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Theme").setDesc("Plotly theme to use by default").addDropdown((dropdown) => dropdown.addOption("plotly_dark", "Dark").addOption("plotly", "Light").addOption("ggplot2", "ggplot2").addOption("seaborn", "Seaborn").setValue(this.plugin.settings.theme).onChange(async (value) => {
      this.plugin.settings.theme = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Background Color").setDesc("Background color of the plot area").addColorPicker((color) => color.setValue(this.plugin.settings.plotBackgroundColor === "rgba(0, 0, 0, 0)" ? "#000000" : this.plugin.settings.plotBackgroundColor).onChange(async (value) => {
      this.plugin.settings.plotBackgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Curve Color").addColorPicker((color) => color.setValue(this.plugin.settings.curveColor).onChange(async (value) => {
      this.plugin.settings.curveColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Grid Color").setDesc("Color of the grid lines and axes").addColorPicker((color) => color.setValue(this.plugin.settings.gridColor).onChange(async (value) => {
      this.plugin.settings.gridColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Text Color").setDesc("Color of the plot labels and text").addColorPicker((color) => color.setValue(this.plugin.settings.textColor).onChange(async (value) => {
      this.plugin.settings.textColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Line Width").setDesc("Thickness of the curves (px)").addSlider((slider) => slider.setLimits(1, 10, 0.5).setValue(this.plugin.settings.lineWidth).onChange(async (value) => {
      this.plugin.settings.lineWidth = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("3D Color Scale").setDesc("Color scale for 3D surfaces and vector fields").addDropdown((dropdown) => dropdown.addOption("Viridis", "Viridis").addOption("Portland", "Portland").addOption("Plasma", "Plasma").addOption("Electric", "Electric").addOption("Hot", "Hot").addOption("Jet", "Jet").setValue(this.plugin.settings.colorscale3D).onChange(async (value) => {
      this.plugin.settings.colorscale3D = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Graph Defaults" });
    new import_obsidian.Setting(containerEl).setName("Default Range Min").setDesc("Starting value for range if not specified").addSlider((slider) => slider.setLimits(-100, 100, 1).setValue(this.plugin.settings.defaultRangeMin).onChange(async (value) => {
      this.plugin.settings.defaultRangeMin = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("Default Range Max").setDesc("Ending value for range if not specified").addSlider((slider) => slider.setLimits(-100, 100, 1).setValue(this.plugin.settings.defaultRangeMax).onChange(async (value) => {
      this.plugin.settings.defaultRangeMax = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    containerEl.createEl("h3", { text: "Performance" });
    new import_obsidian.Setting(containerEl).setName("Render Quality").setDesc("Higher values = smoother plots but slower (Default: 40)").addSlider((slider) => slider.setLimits(10, 100, 5).setValue(this.plugin.settings.renderQuality).onChange(async (value) => {
      this.plugin.settings.renderQuality = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
  }
};

// math-plotly-viewer/main.ts
var MathPlotPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("Math Plotly: Loading plugin...");
    await this.loadSettings();
    try {
      const pluginDir = this.manifest.dir;
      const adapter = this.app.vault.adapter;
      const injectScript = (fileName, globalVar) => {
        return new Promise((resolve) => {
          if (window[globalVar])
            return resolve(window[globalVar]);
          const resourcePath = adapter.getResourcePath((0, import_obsidian2.normalizePath)(pluginDir + "/" + fileName));
          const script = document.createElement("script");
          script.src = resourcePath;
          script.type = "text/javascript";
          script.onload = () => {
            console.log(`MathPlotly: Library ${fileName} loaded.`);
            resolve(window[globalVar]);
          };
          script.onerror = (e) => {
            console.error(`MathPlotly: Failed to load ${fileName}`, e);
            resolve(null);
          };
          document.head.appendChild(script);
        });
      };
      await injectScript("math.min.js", "math");
      await injectScript("plotly.min.js", "Plotly");
      this.registerMarkdownCodeBlockProcessor("plot", (source, el, ctx) => {
        const container = el.createEl("div", { cls: "mathplot-container" });
        const child = new MathPlotRenderChild(container, source, this);
        ctx.addChild(child);
      });
      this.addSettingTab(new MathPlotSettingTab(this.app, this));
    } catch (e) {
      console.error("Math Plotly: Init error", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.onSettingsChange)
      this.onSettingsChange();
    const containers = document.querySelectorAll(".mathplot-container");
    containers.forEach((node) => {
      const htmlNode = node;
      const source = htmlNode.dataset.source;
      if (source) {
        renderPlot(htmlNode, source, this.settings);
      }
    });
  }
};
var MathPlotRenderChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(containerEl, source, plugin) {
    super(containerEl);
    this.source = source;
    this.plugin = plugin;
    this.unloadCallbacks = [];
  }
  registerOnUnload(callback) {
    this.unloadCallbacks.push(callback);
  }
  onunload() {
    this.unloadCallbacks.forEach((cb) => cb());
    super.onunload();
  }
  onload() {
    setTimeout(() => {
      if (this.containerEl) {
        try {
          renderPlot(this.containerEl, this.source, this.plugin.settings, this);
        } catch (e) {
          console.error("MathPlotly render error:", e);
        }
      }
    }, 0);
  }
};
